version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - AI_RECEPTION_REDIS_URL=redis://redis:6379/0
      - AI_RECEPTION_SUPABASE_URL=${AI_RECEPTION_SUPABASE_URL}
      - AI_RECEPTION_SUPABASE_KEY=${AI_RECEPTION_SUPABASE_KEY}
      - AI_RECEPTION_SUPABASE_SERVICE_ROLE_KEY=${AI_RECEPTION_SUPABASE_SERVICE_ROLE_KEY}
    depends_on:
      - redis
    volumes:
      - ./logs:/var/log/supervisor

volumes:
  redis_data:
