name: Build and Deploy to Azure Web App

on:
  push:
    branches: [ development, main ]
  workflow_dispatch:

env:
  ACR_NAME: securetrack
  WEBAPP_NAME: my-ai-receptionist
  RG_NAME: RG-EU-STB-PRD-01
  IMAGE_NAME: air_backend

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout the repo
      - name: "Checkout GitHub repository"
        uses: actions/checkout@v4

      # 2) Login to Azure using the service principal
      - name: "Login to Azure"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANT_ID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTION_ID }}

      # 3) Setup buildx
      - uses: docker/setup-buildx-action@v3

      # 4) Log in to ACR
      - name: "Log in to ACR"
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Fetch ACR loginServer
        id: acr
        run: |
          echo "LOGIN_SERVER=$(az acr show --name ${{ env.ACR_NAME }} \
                            --query loginServer --output tsv)" >> $GITHUB_ENV

      - name: Decide slot, tag and ENV
        id: decide
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "SLOT=" >> $GITHUB_OUTPUT
            echo "TAG=prod-${GITHUB_SHA}" >> $GITHUB_OUTPUT
          else
            echo "SLOT=dev" >> $GITHUB_OUTPUT
            echo "TAG=dev-${GITHUB_SHA}" >> $GITHUB_OUTPUT
          fi

      # 5) Build+push multi-arch (we only target amd64 here)
      - name: Build & push amd64 image
        run: |
          docker buildx build \
            --pull --no-cache \
            --platform linux/amd64 \
            --push \
            --tag $LOGIN_SERVER/${{ env.IMAGE_NAME }}:${{ steps.decide.outputs.TAG }} \
            --file Dockerfile \
            .

      # 6) Setup Python for Migrations
      - name: "Setup Python for Migrations"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 7) Install Python Dependencies for Migrations
      - name: "Install Python Dependencies"
        run: |
          pip install --upgrade pip
          pip install -r app/requirements.txt

      # 8) Run Database Migrations
      - name: "Run Database Migrations"
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "Running production migrations..."
            python app/migrations/migration_runner.py --env prod
          else
            echo "Running development migrations..."
            python app/migrations/migration_runner.py --env dev
          fi
        env:
          SUPABASE_URL_DEV: ${{ secrets.SUPABASE_URL_DEV }}
          SUPABASE_ANON_KEY_DEV: ${{ secrets.SUPABASE_ANON_KEY_DEV }}
          SUPABASE_URL_PROD: ${{ secrets.SUPABASE_URL_PROD }}
          SUPABASE_ANON_KEY_PROD: ${{ secrets.SUPABASE_ANON_KEY_PROD }}

      # 9) Deploy the new image to Azure Web App
      - name: "Deploy to Azure Web App / slot"
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: ${{ steps.decide.outputs.SLOT }}
          # images: ${{ env.ACR_NAME }}-dzc8a3deejhje7d4.azurecr.io/${{ env.IMAGE_NAME }}:latest
          images: ${{ env.LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.decide.outputs.TAG }}
